### ISSUE TITLE
Hello There :D

### ISSUE THREAD

**Issue by TheSunIsADeadlyLaser** [LiamMCW/inventorytabs#2]
I'm very interested in trying out the 1.17 forks of this mod, not quite so much in setting up craddle. yarn and every other utility for building the mod from provided materials D:

if that's not too much of a bother, I jumbly ask you to upload a complete .jar file of a mod under Release tag. If you consider it too tiresome, feel free to close the issue, since it's just me being stupid and not self-sustainable :P
in any way, thanks a lot for forking it

**Comment by LiamMCW** [comment]
I build a jar and made a release, but I might also include a section in the README about compiling yourself because its safer and its not super difficult using gradlew. Keep in mind that this port isn't complete as I removed the server code and haven't done much testing.
